### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by pebenito** [TresysTechnology/setools#105]
When main distributions are ready (Fedora, Gentoo, Debian (AOSP?)) drop Python 2.7 support.
- [x] Exception chaining #106 
- [x] Unconditional ipaddress module use #107 
- [x] Nodecon network property returns IPNetwork objects #108 
- [x] Python 3 is all new-style classes by default #109
- [x] List .clear() method #110  
- [x] IOError was merged into OSError
